name: Check Commit Message

description: Check if commit message is valid

outputs:
  is_commit_message_valid:
    description: "Return True if commit message is valid"
    value: ${{ steps.check_commit_message_script.outputs.is_commit_message_valid }}


runs:
  using: "composite"
  steps:

    - name: Run Python Script
      id: check_commit_message_script
      shell: bash
      run: |
        # Install dependencies
        pip install -r $GITHUB_ACTION_PATH/requirements.txt

        # Exec the sciprt
        output=$(python $GITHUB_ACTION_PATH/check_commit_message.py \
          --commit_hash "${{ github.event.after }}")

        # Print the whole script output for debugging
        echo "$output"

        # Extract the result of the script
        is_commit_message_valid=$(echo "$output" | grep '^is_commit_message_valid=')

        # Add the result to output buffer
        echo "$is_commit_message_valid" >> $GITHUB_OUTPUT
