name: Check Commit Message

description: Check if commit message is valid

runs:
  using: "composite"
  steps:

    - name: echo event
      shell: bash
      run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}

    - name: Run Python Script
      id: check_commit_message_script
      shell: bash
      run: |
        # Install dependencies
        pip install -r $GITHUB_ACTION_PATH/requirements.txt

        # Exec the script
        output=$(python $GITHUB_ACTION_PATH/check_commit_message.py \
          --commit_hash "${{ github.event.after }}")

        # Print the whole script output for debugging
        echo "$output"
