blank_issues_enabled: false
contact_links:
  - name: Facebook Group
    url: https://www.facebook.com/groups/754317328317348
    about: Join our Facebook group for project directions and updates.
  - name: Discord Channel
    url: https://discord.gg/jgVJCaaAPH
    about: Join our Discord server for discussions and announcements.
