name: Check Commit Message

runs:
  using: "composite"
  steps:
    - run: |
        git log --pretty=format:"%s" ${{ github.event.before }}..${{ github.event.after }} | while read -r line; do
          if ! grep -E '^\[issue:[0-9]+\]\n.+' <<< "$line"; then
            echo "Commit messages must start with '[issue:<issue-number>]' followed by a new line and any content."
            echo "Example: [issue:15]\n\nAdd new function to do\nFix typo in"
            exit 1
          fi
        done
